[package]
name = "vivara"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12.0"

twilight = "0.6.0"
twilight-model = "0.6.4"
twilight-embed-builder = "0.6.0"

tracing-subscriber = "0.2.24"

[dependencies.twilight-gateway]
version = "0.6.4"
features = ["zlib-simd"]

[dependencies.twilight-http]
version = "0.6.5"
features = ["simd-json"]

[dependencies.songbird]
version = "0.2.0"
default-features = false
features = ["driver", "gateway", "twilight-rustls", "zlib-simd"]

[dependencies.simd-json]
version = "0.4.7"
features = ["allow-non-simd"]
